### ISSUE TITLE
issue in creating .npy and issue in blender

### ISSUE THREAD

**Issue by ramyagopinathpsg** [val-iisc/pose_estimation#3]
python make_disparity_syn.py
/home/ramya/data/datasets/ShapeNetCore/ShapeNetCore.v1/03001627/13fdf00cde077f562f6f52615fb75fca/model.obj
Traceback (most recent call last):
  File "make_disparity_syn.py", line 29, in make_disparity
    key_3d = run_proj.get_keypoints(model_file)
  File "render_wt_pt_proj/run_proj.py", line 19, in get_keypoints
    mesh[0] = mesh[0].union(mesh[j])
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/trimesh/base.py", line 2461, in union
    engine=engine)
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/trimesh/boolean.py", line 36, in union
    result = _engines[engine](meshes, operation='union')
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/trimesh/boolean.py", line 61, in boolean_automatic
    result = interfaces.blender.boolean(meshes, operation)
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/trimesh/interfaces/blender.py", line 47, in boolean
    ' --background --python $script')
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/trimesh/interfaces/generic.py", line 70, in run
    stderr=subprocess.STDOUT)
  File "/home/ramya/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/blender', '--background', '--python', '/tmp/tmpwx00pgzt']' died with <Signals.SIGSEGV: 11>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_disparity_syn.py", line 80, in <module>
    main()
  File "make_disparity_syn.py", line 77, in main
    make_disparity(args.class_name)
  File "make_disparity_syn.py", line 32, in make_disparity
    key_3d = np.load('/home/ramya/data/sample_points/'+model_synset+'_'+template_model+'.npy')
  File "/home/ramya/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ramya/data/sample_points/03001627_13fdf00cde077f562f6f52615fb75fca.npy'

**Comment by BardOfCodes** [comment]
Hi @ramyagopinathpsg!
Sorry for the delay. I seems like you have not ran the `make_dense_pointset_syn.py` script which will provide the missing sample point file.
Let me know if running the file fixes the issue!

**Comment by ramyagopinathpsg** [comment]
~/pose_estimation/data_creator$ python make_dense_pointset_syn.py --class_name chair
4 0
5 1
6 2
7 3
4 5
5 6
6 7
7 4
7 8
8 9
9 6
10 12
11 13
(3, 130)
 yes i ran it.  Once i ran this file, i ran the next command.. but its giving the same error as mentioned above

**Comment by BardOfCodes** [comment]
@ramyagopinathpsg you will need the Anchor points. 
I forgot uploading them.
They are present here: 
https://drive.google.com/open?id=1_UUmDrM-Bg5KMbHJS-qtiscIsYkWi1_a
